# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  # Se não tiveres o plugin vagrant-vbguest, comenta a linha abaixo:
  # config.vbguest.auto_update = false

  # --- Webserver ---
  config.vm.define "webserver" do |web_config|
    web_config.vm.box = "ubuntu/trusty64"
    web_config.vm.hostname = "webserver"
    web_config.vm.network "private_network", ip: "192.168.56.21"
    web_config.vm.network "forwarded_port", guest: 80, host: 8010
    web_config.vm.provider "virtualbox" do |vb|
      vb.name = "webserver"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "256"
    end
    web_config.vm.provision "shell", path: "bootstrap_web.sh"
  end

  # --- Client ---
  config.vm.define "client" do |client_config|
    client_config.vm.box = "ubuntu/trusty64"
    client_config.vm.hostname = "client"
    client_config.vm.network "private_network", ip: "192.168.56.22"
    client_config.vm.provider "virtualbox" do |vb|
      vb.name = "client"
      vb.memory = "256"
    end
    # Adiciona um script de provisionamento se tiveres um (por exemplo):
    # client_config.vm.provision "shell", path: "bootstrap_client.sh"
  end
end
